linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    shadow: true
    enable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    rules:
    - name: dot-imports
      arguments:
      - allowedPackages:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
  gosec:
    excludes:
    - G115

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - goimports
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  issues-exit-code: 1
issues:
  exclude-dirs:
    - test
