apiVersion: gateway.tv2.dk/v1alpha1
kind: GatewayClassConfig
metadata:
  name: aws-alb-crossplane-dev-env
  namespace: gateway-controller
spec:
  override:
    vpcId: vpc-0e4501e0fbc404284
    subnets:
      subnetId1: subnet-045141a3fdf9d7bb9
      subnetId2: subnet-094508a77cf895ec9
      subnetId3: subnet-099f1b955e66e1a4a
  targetRef:
    group: gateway.networking.k8s.io
    kind: GatewayClass
    name: aws-alb-crossplane
