controllerManager:
  manager:
    rbac:
      additionalPermissions:
      - apiGroups:
        - networking.k8s.io
        resources:
        - ingresses
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
