apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-controller.fullname" . }}-controller-manager
  labels:
    {{- include "gateway-controller.labels" . | nindent 4 }}
  {{- with .Values.controllerManager.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "gateway-controller.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.controllerManager.deploymentStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "gateway-controller.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /gateway-controller
        {{- if (contains "sha256:" .Values.controllerManager.manager.image.tag) }}
          image: "{{ .Values.controllerManager.manager.image.repository }}/{{ .Values.controllerManager.manager.image.name }}@{{ .Values.controllerManager.manager.image.tag }}"
          {{- else }}
        image: {{ .Values.controllerManager.manager.image.repository }}/{{ .Values.controllerManager.manager.image.name }}:{{ .Values.controllerManager.manager.image.tag }}
          {{- end }}
        imagePullPolicy: {{ .Values.controllerManager.manager.image.pullPolicy }}
        name: manager
        livenessProbe: {{- toYaml .Values.controllerManager.manager.livenessProbe | nindent 10 }}
        readinessProbe: {{- toYaml .Values.controllerManager.manager.readinessProbe | nindent 10 }}
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "gateway-controller.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
