apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gateway-controller.fullname" . }}-manager-role
  labels:
    {{- include "gateway-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.tv2.dk
  resources:
  - gatewayclassblueprints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.tv2.dk
  resources:
  - gatewayclassblueprints/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.tv2.dk
  resources:
  - gatewayclassblueprints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.tv2.dk
  resources:
  - gatewayclassconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.tv2.dk
  resources:
  - gatewayclassconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.tv2.dk
  resources:
  - gatewayclassconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.tv2.dk
  resources:
  - gatewayconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.tv2.dk
  resources:
  - gatewayconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.tv2.dk
  resources:
  - gatewayconfigs/status
  verbs:
  - get
  - patch
  - update
{{ with .Values.controllerManager.manager.rbac.additionalPermissions }}
  {{- toYaml . }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gateway-controller.fullname" . }}-manager-rolebinding
  labels:
    {{- include "gateway-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "gateway-controller.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "gateway-controller.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'