apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gateway-controller.fullname" . }}-proxy-role
  labels:
    {{- include "gateway-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gateway-controller.fullname" . }}-proxy-rolebinding
  labels:
   {{- include "gateway-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "gateway-controller.fullname" . }}-proxy-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "gateway-controller.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'