apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: aws-alb-crossplane-public
spec:
  controllerName: "github.com/tv2-oss/bifrost-gateway-controller"
  description: "Internet-facing AWS ALB and Istio ingress gateway"
  parametersRef:
    group: gateway.tv2.dk
    kind: GatewayClassBlueprint
    name: aws-alb-crossplane
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: aws-alb-crossplane-internal
spec:
  controllerName: "github.com/tv2-oss/bifrost-gateway-controller"
  description: "Internal AWS ALB and Istio ingress gateway"
  parametersRef:
    group: gateway.tv2.dk
    kind: GatewayClassBlueprint
    name: aws-alb-crossplane
