controllerManager:
  manager:
    image:
      repository: ghcr.io/tv2-oss/gateway-controller
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8081
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8081
      initialDelaySeconds: 5
      periodSeconds: 10
  annotationer: {}
  replicas: 1
  deploymentStrategy:
    type: Recreate

serviceAccount:
  create: true
  annotations: {}

metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
