# Default values for gateway-controller

controllerManager:
  # controller-manager deployment configuration
  manager:

    image:
      repository: ghcr.io/tv2-oss
      name: gateway-controller
      tag: latest
      pullPolicy: IfNotPresent

    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

    livenessProbe:
      httpGet:
        path: /healthz
        port: 8081
      initialDelaySeconds: 15
      periodSeconds: 20

    readinessProbe:
      httpGet:
        path: /readyz
        port: 8081
      initialDelaySeconds: 5
      periodSeconds: 10

  # Annotations to add to the deployment
  annotations: {}
  replicas: 1

  deploymentStrategy:
    type: Recreate

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
